version: "3.8"

networks:
  inception:
    driver: bridge

volumes:
  mariadb:
    driver_opts:
      type: none
      device: /home/lbiasuz/data/mysql
      o: bind

  wordpress:
    driver_opts:
      type: none
      device: /home/lbiasuz/data/html
      o: bind

services:
  mariadb:
    build: requirements/mariadb/
    container_name: mariadb
    image: mariadb
    restart: on-failure
    environment:
      - DB_NAME=${MYSQL_DATABASE}
      - DB_USER=${MYSQL_USER}
      - DB_PASSWORD=${MYSQL_PASSWORD}
      - DB_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    networks: 
      - inception
    volumes:
      - mariadb:/var/lib/mysql
    
  wordpress:
    depends_on:
      - mariadb
    build: requirements/wordpress
    container_name: wordpress
    image: wordpress
    restart: on-failure
    env_file: .env
    networks: 
      - inception
    volumes:
      - wordpress:/var/www/html/

  nginx:
    depends_on:
      - wordpress
    build: requirements/nginx
    container_name: nginx
    image: nginx
    restart: on-failure
    env_file: .env
    ports:
      - "443:443"
    networks: 
      - inception
    volumes:
      - wordpress:/var/www/html/